### ISSUE TITLE
append rec to already existing file

### ISSUE THREAD

**Issue by abisuman** [daichirata/fluent-plugin-gcs#11]
Currently there is no option to append rec to existing file.  It can overwrite entire file or through error that file already exist based on overwrite parameter. For append it says not used.   Is there any way to append data to existing file

**Comment by daichirata** [comment]
Google Cloud Storage objects are immutable, so we can't append records.https://cloud.google.com/storage/docs/key-terms?hl=en#immutability

if there is a possibility of duplicate object paths, consider using the index of object_key_format.

```
%{index} is the sequential number starts from 0, increments when multiple files are uploaded to GCS in the same time slice.
```

Alternatively, setting timekey_wait may solve the problem. 
https://docs.fluentd.org/v1.0/articles/buffer-section

**Comment by abisuman** [comment]
Consider having 4 apache servers and we want logs of all 4 to be centralized. Which is the best way to do it.

**Comment by daichirata** [comment]
Roger that, I hope your problem will be solved.

**Comment by abisuman** [comment]
Problem is still there.
