### ISSUE TITLE
Migrate to Fluentd v0.14 API

### ISSUE THREAD

**Issue by daichirata** [daichirata/fluent-plugin-gcs#5]

**Comment by cosmo0920** [comment]
Hi, I've registered a PR which uses v0.14 API.
Could you take a look?

Thanks, a lot.

**Comment by axot** [comment]
Does this plugin support multi process workers in fluentd 0.14 version

**Comment by cosmo0920** [comment]
Yup. https://github.com/daichirata/fluent-plugin-gcs/blob/master/lib/fluent/plugin/out_gcs.rb#L115

**Comment by axot** [comment]
@cosmo0920 We suffered performance issues even setup 8 workers, is there some method can debug this issue?

```
ls -l /var/log/td-agent/buffer/gcs/worker* | wc -l
15231
```

**Comment by cosmo0920** [comment]
I'm not a psychic.
But, in general, increasing chunk and writing interval will solve performance issue.

**Comment by axot** [comment]
The problem now is throughput of 1 worker vs 8 workers has no significant difference. Did the project perform a benchmark for amount of workers?

**Comment by cosmo0920** [comment]
multi workers feature relies on Fluentd core feature.
Could you send your question in https://groups.google.com/forum/#!forum/fluentd or https://fluent-all.slack.com/ with more detailed use case and your Fluentd config which is not included sensitive information?
It would be helpful for core developers.
