### ISSUE TITLE
Failed flush because of Zlib::DataError

### ISSUE THREAD

**Issue by anthonyhaussman** [daichirata/fluent-plugin-gcs#9]
Hi,

I have set a fluentd (version 1.2.5) broker configuration to set some logs data into gcs.
With a simple config where I set the buffer at 5m and using buffer time, everything works great:

```
    path toto
    time_slice_format '%Y-%m-%d_%H%M'
    object_key_format %Y/%m/%d/%{time_slice}_%{hostname}_%{uuid_flush}_%{index}_%{path}.%{file_extension}
    utc

    <buffer time>
      @type file
      path /data/fluent/toto
      timekey 5m
      timekey_wait 0s
      timekey_use_utc true
      flush_at_shutdown true
    </buffer>
```

Now the thing is I want to add the tag who represent the hostname of the server who has forward the log. Te be more specific, It is about 400 hosts who sent their logs:

```
    path ${tag[1]}_toto  #  ${tag[1]} represent the hostname of one fowarder
    time_slice_format '%Y-%m-%d_%H%M'
    object_key_format %Y/%m/%d/%{time_slice}_%{hostname}_%{uuid_flush}_%{index}_%{path}.%{file_extension}
    utc

    <buffer tag,time>
      @type file
      path /data/fluent/toto
      timekey 5m
      timekey_wait 0s
      timekey_use_utc true
      flush_at_shutdown true
    </buffer>
```

But with this settings, fluentd report a lot of error about Zlib:

`
2018-10-02 18:03:43 +0200 [warn]: #20 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-10-02 18:03:44 +0200 chunk="57741037bffabce665f0c6a2247d13e8" error_class=Zlib::DataError error="data error"
`

After a retry, it succeeds:

`
2018-10-02 18:03:45 +0200 [warn]: #20 retry succeeded. chunk_id="57741037bffabce665f0c6a2247d13e8"
`

If someone has an idea.

**Comment by daichirata** [comment]
Thank you for telling us the fluentd fix.
This issue is closed, but please report it again if something goes wrong.
